"""initial schema

Revision ID: 20adb30d59a8
Revises:
Create Date: 2026-04-04 14:38:18.303916
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20adb30d59a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letters",
        sa.Column("dead_letter_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("dead_letter_id"),
    )
    op.create_table(
        "edges",
        sa.Column("edge_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id_source", sa.Uuid(), nullable=True),
        sa.Column("rule_id_target", sa.Uuid(), nullable=True),
        sa.Column("relationship_type", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("extraction_method", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("edge_id"),
    )
    op.create_table(
        "rules",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("agency", sa.Text(), nullable=False),
        sa.Column("document_type", sa.Text(), nullable=False),
        sa.Column("cfr_sections", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("administration", sa.Text(), nullable=False),
        sa.Column("fr_url", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("rule_id"),
        sa.UniqueConstraint("content_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rules")
    op.drop_table("edges")
    op.drop_table("dead_letters")
    # ### end Alembic commands ###
